language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - 'pypy'

before_install:
  - sudo apt-get install strace

install:
  - "pip install . --use-mirrors"
  # See https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

branches:
  only:
    - master
    - test


script: py.test

notifications:
    email:
        on_success: change
        on_failure: change
